sudo: required
dist: trusty
language: c
compiler:
  - arm-none-eabi-gcc
cache:
  directories:
    - "${HOME}/persist"


before_install:
  - sudo apt install build-essential
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded
  - git clone https://github.com/beckus/qemu_stm32
  - cd qemu_stm32
  - ./configure --disable-werror --enable-debug \
        --target-list="arm-softmmu" \
        --extra-cflags=-DDEBUG_CLKTREE \
        --extra-cflags=-DDEBUG_STM32_RCC \
        --extra-cflags=-DDEBUG_STM32_UART \
        --extra-cflags=-DSTM32_UART_NO_BAUD_DELAY \
        --extra-cflags=-DSTM32_UART_ENABLE_OVERRUN --python=python2
  - make -j8
  - cd ..


before_script:
  - arm-none-eabi-gcc --version

script:
  - make TARGET=stm32p103 -j4
